server:
  port: 8080
  servlet:
    context-path: /blog

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: blog
    password: blog
    url: jdbc:mariadb://localhost:3307/blog?serverTimezone=Asia/Seoul

  # create, update, none, create-drop. validate
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update

      # Entity naming --> camelCase // physical-strategy
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      # Entity naming --> CamelCase -> underscores
      # naming.physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      # not use the jpa-auto-id-generator
      use-new-id-generator-mappings: false

    # Jpa Properties
    properties:
      hibernate:
        show_sql: true
        format_sql: true